import { Button, ThemeConfig, UIProvider } from "@yamada-ui/react"
import { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";
import "./globals.css";
import { ColorModeScript, defaultConfig} from "@yamada-ui/react"
import Sns from "@/components/sns";

const inter = Inter({ subsets: ["latin"] });

const navItems = [
  { label: "Home", href: "/" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
]

export const metadata: Metadata = {
  title: {
    template: "%s | leo",
    default: "leo",
  },
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <UIProvider>
          
          <header className="container mx-auto h-16 flex items-center border-b justify-between px-4">
            <h1 className="font-bold text-2xl">
              <Link href="/">
                <img src="/logo.png" alt="Icon" className="size-10" />
              </Link>
            </h1>
            <ul className="flex gap-1">
              {navItems.map((item) => (
                <li key={item.label}>
                  <Button colorScheme="sky" variant="ghost" size="sm">
                    <Link href={item.href}>{item.label}</Link>
                  </Button>

                </li>
              ))}
              <Button colorScheme="sky" variant="ghost" size="sm">Color</Button>
            </ul>
          </header>

          <main className="flex-grow container mx-auto px-4">
            {children}
          </main>

          <footer className="container mx-auto h-16 flex items-center justify-between border-t">
            <p className="text-sm">&copy;2024 leo</p>
            <Sns />
          </footer>
        </UIProvider>        
      </body>
    </html>
  );
}

